services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-moneda
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monedadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conversor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: conversor-moneda-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/monedadb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_LOG_LEVEL: INFO
    networks:
      - conversor-network

  # Opcional: PgAdmin para administrar la base de datos visualmente
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-moneda
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - conversor-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  conversor-network:
    driver: bridge