version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monedadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - conversor-network

  # Opcional: PgAdmin para administrar la base de datos visualmente
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-moneda
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - conversor-network

volumes:
  postgres_data:

networks:
  conversor-network:
    driver: bridge